name: Build artifacts

# push & pr everywhere in order to test
on: [push, pull_request]

#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:
  build:    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel setuptools
    
    - name: Build tar.gz
      run: python3 setup.py sdist
    
    - name: Build wheel
      run: python3 setup.py bdist_wheel
      
    - name: Get version
      run: echo "BIN_VERSION=$(cat VERSION)" >> $GITHUB_ENV
    
    - name: Upload tar.gz
      uses: actions/upload-artifact@v2.2.1
      with:
        name: bin-archive
        path: dist/bin-${{ env.BIN_VERSION }}.tar.gz

    - name: Upload wheel
      uses: actions/upload-artifact@v2.2.1
      with:
        name: bin-wheel
        path: dist/bin-${{ env.BIN_VERSION }}-py3-none-any.whl
