name: CD - Build and release packages

on:
  push:
    branches: [main]

jobs:
  release-please:
    runs-on: ubuntu-latest

    steps:
    - uses: GoogleCloudPlatform/release-please-action@v2
      outputs:
        released: ${{ steps.release.outputs.release_created }}
        tag: ${{ steps.release.outputs.tag }}
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        release-type: simple
        default-branch: main

  build:
    runs-on: ubuntu-latest
    needs: [release-please]
    if: ${{ needs.release-please.outputs.released }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel setuptools
    
    - name: Build tar.gz
      run: python3 setup.py sdist
    
    - name: Build wheel
      run: python3 setup.py bdist_wheel
    
    - name: Upload tar.gz and wheel
      uses: svenstaro/upload-release-action@v2
      with:
        file: dist/*
        file_glob: true
        tag: ${{ needs.release-please.outputs.tag }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
